yeasesul
GDSC-SKHU/GDSC-Web-Study-01 pull request #12
Opened 2022-11-02 15:24 UTC by yeaseul7

## Description

> 구현 및 작업 내용을 적어주세요.

-
-
-

## Important content

> 주의 깊게 봐야 하거나 말하고 싶은 점을 적어주세요.

-
-
-

## Reference

> 참고한 레퍼런스가 있다면 기록해주세요.

2022-11-02 15:37 UTC, hanseulhee requested changes
예슬님 pr 제목 컨벤션에 맞게 맞춰주시고 .DS_Store 파일 삭제해주세요 ~!

https://dlee0129.tistory.com/250

2022-11-03 04:28 UTC, hyesungoh commented
예슬님 리드미랑 `.DS_Store` 파일 제가 수정한 후에 리뷰 남겨 드릴게요 ~

2022-11-03 04:43 UTC, hyesungoh approved these changes
👍 👍

2022-11-03 04:43 UTC, hyesungoh commented on 이예슬/index.css
> +    color: rgb(197, 219, 255);
👍 👍

2022-11-03 04:43 UTC, hyesungoh commented on 이예슬/index.html
> +            <!-- tip 같은 요소 3개 있을때 option+shift+방향키 -> 복붙 -->
💯

2022-11-03 04:43 UTC, hyesungoh commented on 이예슬/index.css
> +    flex-direction: column;
```suggestion
    display: flex;
    align-items: center;
    padding: 0 20px;
    font-size: 1.875rem;
    flex-direction: column;
```
두 번 쓰신 요소가 있어요 ~

2022-11-03 04:51 UTC, hanseulhee approved these changes
수고하셨어요 👍🏻👍🏻👍🏻 😄

2022-11-03 04:51 UTC, hanseulhee commented on 이예슬/index.html
> +            <img class="hobby" src="./img/df934e40d28dae33b9ea8a85aa4569cbd455c616511712c93d878a3cd9d98863109ab1bd99ef31f826c93cd25086ce0fa9a649c33dd1c1bf19577ceb2cf8aa7070751e03ae1c5a7bd5662df37bf82
img 태그에 alt 속성값을 넣어주세요 ~!

2022-11-03 04:54 UTC, merged